# Generated by Django 5.2.7 on 2025-10-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_invoice_pdf',
            field=models.URLField(blank=True, null=True),
        ),
    ]
