# Generated by Django 5.2.6 on 2025-10-10 23:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiques', '0002_alter_antique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antique',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
