# Generated by Django 5.2.6 on 2025-10-11 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiques', '0004_antique_updated_at_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='antique',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='antiques',
            field=models.ManyToManyField(blank=True, related_name='wishlists', to='antiques.antique'),
        ),
    ]
