# Generated by Django 5.2.6 on 2025-10-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiques', '0006_remove_wishlist_user_wishlist_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='antique',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='antique',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
