# Generated by Django 5.2.6 on 2025-10-11 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiques', '0007_antique_content_alter_antique_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antique',
            name='image',
        ),
        migrations.CreateModel(
            name='AntiqueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='antiques/')),
                ('antique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='antiques.antique')),
            ],
        ),
    ]
