# Generated by Django 5.2.6 on 2025-10-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiques', '0008_remove_antique_image_antiqueimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='antique',
            name='short_id',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
