# Generated by Django 5.2.6 on 2025-10-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiques', '0010_dailypick'),
    ]

    operations = [
        migrations.AddField(
            model_name='antique',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='antique',
            name='dimensions',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='antique',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
