# Generated by Django 5.2.6 on 2025-10-11 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seller'),
        ('antiques', '0011_antique_additional_info_antique_dimensions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='antique',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='antiques', to='accounts.seller'),
        ),
    ]
