# Generated by Django 5.2.6 on 2025-10-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("antiques", "0012_antique_seller"),
    ]

    operations = [
        migrations.AddField(
            model_name="antique",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="antique",
            name="stripe_product_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
