# Generated by Django 5.2.6 on 2025-10-15 23:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_emailverification"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailverification",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="emailverification",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="emailverification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_verifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
